
import React from 'react';
import { Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface AssessmentReviewProps {
  assessment: {
    grade: string;
    feedback: string;
  };
  onApprove: () => void;
  onReset: () => void;
}

const AssessmentReview = ({ assessment, onApprove, onReset }: AssessmentReviewProps) => {
  return (
    <>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-gray-50 p-4 rounded-lg text-center">
          <h3 className="text-sm font-medium text-gray-500 mb-1">Grade</h3>
          <p className="text-4xl font-bold gradient-text">{assessment.grade}</p>
        </div>
        <div className="md:col-span-2 bg-gray-50 p-4 rounded-lg">
          <h3 className="text-sm font-medium text-gray-500 mb-2">Feedback</h3>
          <p className="text-sm">{assessment.feedback}</p>
        </div>
      </div>
      
      <Alert className="mt-6" variant="default">
        <Info className="h-4 w-4" />
        <AlertTitle>AI-Powered Assessment</AlertTitle>
        <AlertDescription className="text-sm">
          This assessment was generated by an AI system. Your teacher may provide additional feedback and adjust the final grade if needed.
        </AlertDescription>
      </Alert>

      <div className="flex flex-col md:flex-row gap-4 mt-6">
        <Button 
          variant="outline" 
          onClick={onReset}
          className="w-full md:w-auto"
        >
          Start Over
        </Button>
        <Button 
          onClick={onApprove} 
          className="w-full md:w-auto blue-purple-gradient hover:opacity-90"
        >
          Approve & Save
        </Button>
      </div>
    </>
  );
};

export default AssessmentReview;
